workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        TAG_NAME: api_server_runner
      when: always
    #- if: $CI_COMMIT_BRANCH == "dev"
 
stages:
- deploy
deploy:
  stage: deploy
  tags:
    - ${TAG_NAME}
  script:
  - docker compose down
  #- docker rmi stock_price_parser_ecomru-ru-app
  - docker compose up -d
  