version: "3.8"

services:
  stock-price-parser-ecomru-ru:
    container_name: stock-price-parser-ecomru-ru
    build: .
    environment:
      TZ: Europe/Moscow
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      SSLMODE: ${SSLMODE}
      TARGET_SESSION_ATTRS: ${TARGET_SESSION_ATTRS}
      ROOT_CERT: ${ROOT_CERT}
      APP_ENV: ${APP_ENV}

    #command: sh script.sh
    
  nginx:
    container_name: nginx-stock-price-parser-ecomru-ru
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - stock-price-parser-ecomru-ru
    restart: always
    environment:
      - "TZ=Europe/Moscow"
    ports:
      - 8096:80
      - 4446:443
      - 5066:5000
