version: "3.8"

services:
  app:
    build: .
    environment:
      TZ: Europe/Moscow
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB: ${PG_DB}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      SSLMODE: ${SSLMODE}
      TARGET_SESSION_ATTRS: ${TARGET_SESSION_ATTRS}
      ROOT_CERT: ${ROOT_CERT}
      APP_ENV: ${APP_ENV}

    command: sh script.sh
    
