###
POST http://localhost:5000/stocks
Content-Type: application/json

{
  "warehouseId": 23605348895000,
  "partnerWarehouseId": "50",
  "skus": [
     "S18DS95",
      "S18DS66",
      "263513128",
      "263513419"
  ]
}